apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-predictor-data
  namespace: f1-predictor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
