apiVersion: v1
kind: Service
metadata:
  name: f1-predictor
  namespace: f1-predictor
  labels:
    app: f1-predictor
spec:
  selector:
    app: f1-predictor
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
