apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-predictor
spec:
  template:
    spec:
      containers:
      - name: f1-predictor
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: API_BASE_URL
          value: ""
        - name: USE_STUB_API
          value: "false"
