apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: f1-predictor-dev

namePrefix: dev-

resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: f1-predictor
  spec:
    template:
      spec:
        containers:
        - name: f1-predictor
          env:
          - name: ENVIRONMENT
            value: "dev"
          - name: API_BASE_URL
            value: ""
          - name: USE_STUB_API
            value: "false"
